config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  if defined?(Sidekiq)
    mount Sidekiq::Web => "/sidekiq"
  end

  root 'pages#index'
  devise_for :users,
    skip: [:registrations],
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }
  devise_scope :user do
    # sessions get
    get '/signin', to: 'users/sessions#new'

    # sessions post
    post '/signin', to: 'users/sessions#create'

    # sessions delete
    delete '/signin', to: 'users/sessions#destroy'
  end

  resources :members, only: [:index, :new, :create, :show, :update, :destroy]
  resources :archived_members, only: [:index, :show, :update, :destroy]
  resources :message_templates, only: [:index, :new, :create]
  resources :sms_messages, only: [:index, :new, :create]
  resources :users, only: [:index, :new, :create, :show, :update, :destroy]

  post '/callbacks/twilio/receive', to: 'callbacks/twilio/message_receiver#create'
  post '/callbacks/twilio/status', to: 'callbacks/twilio/message_receiver#update'

  get "/google/calendars", to: "callbacks/google/calendars#index"
  get "/google/oauth2callback", to: "callbacks/google/calendars#oauth2callback"
  # get "/callbacks/google", to: "callbacks/google/calendars#callback"
  # get "/callbacks/google/calendars", to: "callbacks/google/calendars#calendars"
  # get "callbacks/google/calendars/events/:calendar_id", to: "callbacks/google/calendars#events", as: "events", calendar_id: "/[^\/]+/"
end

app/models/sms_message.rb
# == Schema Information
#
# Table name: sms_messages
#
#  id              :bigint           not null, primary key
#  delivery_status :integer
#  from_number     :string
#  message_body    :string
#  message_sid     :string
#  outbound        :boolean
#  segment_count   :integer
#  to_number       :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_sms_messages_on_message_sid  (message_sid) UNIQUE
#
class SmsMessage < ApplicationRecord
  enum delivery_status: { queued: 0, pending: 1, sent: 2, delivered: 3, undelivered: 4, failed: 5, received: 6 }
end

app/controllers/sms_messages_controller.rb
class SmsMessagesController < ApplicationController
  def index
    @messages = SmsMessage.all.order(created_at: :desc).page(params[:page])
  end

  def new
    @options = [ { "volunteers" => "All Volunteers", "students" => "All Students" } ]
  end

  def create
    BulkMessageSenderJob.perform_async(create_params[:member_scope], create_params[:message])
    flash[:success] = "Message sent!"

    redirect_to action: :new
  end

  private

  def create_params
    params.require(:sms_message).permit(:member_scope, :message)
  end
end

app/helpers/sms_messages_helper.rb
module SmsMessagesHelper
end

app/views/sms_messages/index.html.erb
<div class="container mt-4">
  <%= button_to "New Message", new_sms_message_path, method: :get, class: "btn btn-primary" %>

  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th>From Number</th>
        <th>To Number</th>
        <th>Outbound</th>
        <th>Segments Count</th>
        <th>Delivery Status</th>
        <th>Body</th>
      </tr>
    </thead>
    <tbody>
      <% @messages.each do |message| %>
        <tr>
          <td><%= message.from_number %></td>
          <td><%= message.to_number %></td>
          <td><%= message.outbound %></td>
          <td><%= message.segment_count %></td>
          <td><%= message.delivery_status %></td>
          <td><%= message.message_body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      <%= paginate @messages %>
    </ul>
  </nav>
</div>

app/views/sms_messages/new.html.erb
<div class="container mt-4">
  <%= form_for :sms_message, url: sms_messages_path, method: :post  do  |f| %>
    <div class="form-group">
      <%= f.label :member_scope, "Select who you want to send a message to" %>
      <div>
        <%= f.select :member_scope, options_for_select(@options.first.values, @options.first.keys.first), {}, { required: true, id: 'member-select', class: "dropdown" } %>
        <%= f.hidden_field :member_scope, id: 'member-scope-value', value: @options.first.keys.first %>
      </div>
      </div>

    <div class="form-group">
      <%= f.label :message, "Message" %>
      <%= f.text_field :message, class: "form-control", id: "message-input", required: true %>
      <small id="character-count" class="form-text text-muted">Character count: 0</small>
      <small id="segments-count" class="form-text text-muted">Segments count: 0</small>
    </div>

    <div class="form-group">
      <%= submit_tag "Send Message", class: "btn btn-primary", onclick: "return confirm('Are you sure you want to send this message?');" %>
    </div>
  <% end %>
</div>