config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  if defined?(Sidekiq)
    mount Sidekiq::Web => "/sidekiq"
  end

  root 'pages#index'
  devise_for :users,
    skip: [:registrations],
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }
  devise_scope :user do
    # sessions get
    get '/signin', to: 'users/sessions#new'

    # sessions post
    post '/signin', to: 'users/sessions#create'

    # sessions delete
    delete '/signin', to: 'users/sessions#destroy'
  end

  resources :members, only: [:index, :new, :create, :show, :update, :destroy]
  resources :archived_members, only: [:index, :show, :update, :destroy]
  resources :message_templates, only: [:index, :new, :create]
  resources :sms_messages, only: [:index, :new, :create]
  resources :users, only: [:index, :new, :create, :show, :update, :destroy]

  post '/callbacks/twilio/receive', to: 'callbacks/twilio/message_receiver#create'
  post '/callbacks/twilio/status', to: 'callbacks/twilio/message_receiver#update'

  get "/google/calendars", to: "callbacks/google/calendars#index"
  get "/google/oauth2callback", to: "callbacks/google/calendars#oauth2callback"
  # get "/callbacks/google", to: "callbacks/google/calendars#callback"
  # get "/callbacks/google/calendars", to: "callbacks/google/calendars#calendars"
  # get "callbacks/google/calendars/events/:calendar_id", to: "callbacks/google/calendars#events", as: "events", calendar_id: "/[^\/]+/"
end

app/views/shared/_alert_modal.html.erb
<div class="modal fade" id="alertModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="alertModalLabel">Alert</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-danger" id="alert-modal-body">
        <%= flash[:alert] %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_global_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <ul class="navbar-nav">
      <li class="nav-item">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= button_to root_path, method: :get, class: "btn btn-primary" do %>
              Home
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to users_path, method: :get, class: "btn btn-primary" do %>
              Users
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to message_templates_path, method: :get, class: "btn btn-primary" do %>
              Message Templates
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to sms_messages_path, method: :get, class: "btn btn-primary" do %>
              Messages
            <% end %>
          </li>
          <li class="nav-item">
            <%= button_to members_path, method: :get, class: "btn btn-primary" do %>
              Members
            <% end %>
          </li>

          <li class="nav-item">
            <%= button_to google_calendars_path, method: :get, class: "btn btn-primary" do %>
              Link Calendar
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to "My Profile", user_path(current_user), class: "btn btn-primary" %>
          </li>

          <li class="nav-item">
            <%= form_for :user, url: destroy_session_path(:user), method: :delete do |f| %>
              <%= f.submit "Sign out", class: "btn btn-danger ml-2" %>
            <% end %>
          </li>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/shared/_success_modal.html.erb
<div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="alertModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="successModalLabel">Success</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body text-success" id="success-modal-body">
        <%= flash[:success] %>
      </div>
    </div>
  </div>
</div>