config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  if defined?(Sidekiq)
    mount Sidekiq::Web => "/sidekiq"
  end

  root 'pages#index'
  devise_for :users,
    skip: [:registrations],
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }
  devise_scope :user do
    # sessions get
    get '/signin', to: 'users/sessions#new'

    # sessions post
    post '/signin', to: 'users/sessions#create'

    # sessions delete
    delete '/signin', to: 'users/sessions#destroy'
  end

  resources :members, only: [:index, :new, :create, :show, :update, :destroy]
  resources :archived_members, only: [:index, :show, :update, :destroy]
  resources :message_templates, only: [:index, :new, :create]
  resources :sms_messages, only: [:index, :new, :create]
  resources :users, only: [:index, :new, :create, :show, :update, :destroy]

  post '/callbacks/twilio/receive', to: 'callbacks/twilio/message_receiver#create'
  post '/callbacks/twilio/status', to: 'callbacks/twilio/message_receiver#update'

  get "/google/calendars", to: "callbacks/google/calendars#index"
  get "/google/oauth2callback", to: "callbacks/google/calendars#oauth2callback"
  # get "/callbacks/google", to: "callbacks/google/calendars#callback"
  # get "/callbacks/google/calendars", to: "callbacks/google/calendars#calendars"
  # get "callbacks/google/calendars/events/:calendar_id", to: "callbacks/google/calendars#events", as: "events", calendar_id: "/[^\/]+/"
end

app/controllers/archived_members_controller.rb
class ArchivedMembersController < ApplicationController
  include MembersSearchable

  def index
    if params[:search].present?
      search_members(archived: true)
    else
      @members = Member.inactive.order(name: :asc).page(params[:page])
    end
  end
end

app/helpers/archived_members_helper.rb
module ArchivedMembersHelper
end

app/views/archived_members/index.html.erb
<div class="container mt-4">

  <%= form_tag(archived_members_path, method: :get) do %>
    <p> Search for a member </p>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
  <% end %>

  <a href="<%= members_path %>" class="btn btn-primary">Members</a>

  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Member Type</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.name %> <%= link_to '(Edit)', member_path(member), 'data-turbolinks': false %></td>
          <td><%= member.email %></td>
          <td><%= member.normalized_phone_number %></td>
          <td><%= member.member_type %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      <%= paginate @members %>
    </ul>
  </nav>
</div>

app/views/archived_members/show.html.erb
<div class="container mt-4">
  <h1>Member Profile</h1>
  <%= form_for @member do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", value: @member.name %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", value: @member.email %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control", value: @member.phone_number %>
    </div>

    <div class="form-group">
      <%= f.label :member_type %>
      <%= f.select :member_type, options_for_select(['volunteer', 'student'], selected: @member.member_type), class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :archived %>
      <%= f.check_box :archived, checked: @member.archived? %>
    </div>

    <div class="form-group">
      <%= f.submit "Save Changes" %>
    </div>
  <% end %>

  <div class="form-group">
    <%= button_to "Delete Member", archived_member_path, method: :delete, class: "btn btn-danger", onclick: "return confirm('Are you sure you want to delete this member?');" %>
  </div>
</div>