config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  if defined?(Sidekiq)
    mount Sidekiq::Web => "/sidekiq"
  end

  root 'pages#index'
  devise_for :users,
    skip: [:registrations],
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    }
  devise_scope :user do
    # sessions get
    get '/signin', to: 'users/sessions#new'

    # sessions post
    post '/signin', to: 'users/sessions#create'

    # sessions delete
    delete '/signin', to: 'users/sessions#destroy'
  end

  resources :members, only: [:index, :new, :create, :show, :update, :destroy]
  resources :archived_members, only: [:index, :show, :update, :destroy]
  resources :message_templates, only: [:index, :new, :create]
  resources :sms_messages, only: [:index, :new, :create]
  resources :users, only: [:index, :new, :create, :show, :update, :destroy]

  post '/callbacks/twilio/receive', to: 'callbacks/twilio/message_receiver#create'
  post '/callbacks/twilio/status', to: 'callbacks/twilio/message_receiver#update'

  get "/google/calendars", to: "callbacks/google/calendars#index"
  get "/google/oauth2callback", to: "callbacks/google/calendars#oauth2callback"
  # get "/callbacks/google", to: "callbacks/google/calendars#callback"
  # get "/callbacks/google/calendars", to: "callbacks/google/calendars#calendars"
  # get "callbacks/google/calendars/events/:calendar_id", to: "callbacks/google/calendars#events", as: "events", calendar_id: "/[^\/]+/"
end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                      :bigint           not null, primary key
#  archived                :boolean          default(FALSE)
#  data                    :jsonb
#  deleted_at              :datetime
#  email                   :string
#  member_type             :integer
#  name                    :string
#  normalized_phone_number :string
#  phone_number            :string
#  unsubscribed            :boolean          default(FALSE)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#
# Indexes
#
#  index_members_on_email                    (email) UNIQUE
#  index_members_on_member_type              (member_type)
#  index_members_on_normalized_phone_number  (normalized_phone_number) UNIQUE
#
class Member < ApplicationRecord
  acts_as_paranoid

  enum member_type: { volunteer: 0, student: 1 }

  validates :phone_number, presence: true, uniqueness: true
  validates :normalized_phone_number, uniqueness: true, unless: :new_record?
  validates :email, uniqueness: true, allow_blank: true

  scope :active, -> { where(archived: false) }
  scope :inactive, -> { where(archived: true) }

  scope :volunteers, -> { where(member_type: 'volunteer') }
  scope :students, -> { where(member_type: 'student') }
  scope :unsubscribed, -> { where(unsubscribed: true) }
  scope :subscribed, -> { where(unsubscribed: false) }

  before_save :normalize_phone_number, if: :phone_number_changed?
  before_save :normalize_email, if: :email_changed?
  after_create :normalize_phone_number, :normalize_email

  has_many :sms_messages, foreign_key: :to_number, primary_key: :normalized_phone_number, dependent: :destroy
  has_many :events

  def subscribed?
    !unsubscribed?
  end

  def unsubscribe
    update!(unsubscribed: true)
  end

  def resubscribe
    update!(unsubscribed: false)
  end

  private

  def normalize_phone_number
    self.normalized_phone_number = PhonyRails.normalize_number(phone_number, default_country_code: 'US')
  end

  def normalize_email
    self.email = email.downcase
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include MembersSearchable

  def new; end

  def show
    @member = Member.find(params[:id])
  end

  def index
    if params[:search].present?
      search_members
    elsif params[:scope] == 'student'
      @members = Member.active.student.order(name: :asc).page(params[:page])
    elsif params[:scope] == 'volunteer'
      @members = Member.active.volunteer.order(name: :asc).page(params[:page])
    else
      @members = Member.active.all.order(name: :asc).page(params[:page])
    end
  end

  def create
    begin
      ActiveRecord::Base.transaction do
        Member.create!(params)
      end
      flash[:success] = "Member created successfully."
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Error creating member: #{e.message}"
    end

    redirect_to members_path
  end

  def destroy
    begin
      ActiveRecord::Base.transaction do
        member = Member.find(destroy_params[:id])
        member.destroy!
      end
      flash[:success] = "Member deleted successfully."
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Error deleting member: #{e.message}"
    end

    redirect_to members_path
  end

  def update
    begin
      ActiveRecord::Base.transaction do
        member = Member.find(params[:id])
        member.update!(parsed_params(member, update_params))
      end
      flash[:success] = "Member updated successfully."
    rescue ActiveRecord::RecordNotFound => e
      flash[:alert] = "Error updating member: #{e.message}"
    rescue ActiveModel::UnknownAttributeError => e
      flash[:alert] = "Error updating member: #{e.message}"
    end

    redirect_to members_path
  end

  private

  def create_params
    params.require(:member).permit(:name, :email, :phone_number, :member_type)
  end

  def update_params
    permitted_params = params.require(:member).permit(
      :name,
      :email,
      :phone_number,
      :member_type,
      :archived,
      :unsubscribed,
      data: {},
    )

    dynamic_params = {
      keys: params[:data_keys],
      values: params[:data_values],
    }

    permitted_params.merge(dynamic_params)
  end

  def destroy_params
    params.permit(:id)
  end

  def parsed_params(member, parameters)
    return unless parameters[:keys].present? && parameters[:values].present?

    parameters[:keys].each_with_index do |key, index|
      safe_key = key&.gsub(/[^a-zA-Z\s]/, '')&.rstrip&.gsub(/\s+/, '_')&.downcase
      value = parameters[:values][index]&.rstrip

      next if safe_key.blank?
      next if value.blank?

      parameters[:data].merge!({ "#{safe_key}" => "#{value}" })
    end

    parameters.delete(:keys)
    parameters.delete(:values)

    parameters
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/index.html.erb
<div class="container mt-4">
  <%= form_tag(members_path, method: :get) do %>
    <p> Search for a member </p>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
  <% end %>

  <div class="mt-4">
    <%= link_to "Create Member", new_member_path, class: "btn btn-primary" %>
    <%= link_to "Archived Members", archived_members_path, class: "btn btn-primary" %>
  </div>

  <div class="mt-4">
    <%= link_to "Student Members", members_path(scope: 'student'), class: "btn btn-primary" %>
    <%= link_to "Volunteer Members", members_path(scope: 'volunteer'), class: "btn btn-primary" %>
  </div>

  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone Number</th>
        <th>Member Type</th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
        <tr>
          <td><%= member.name %> <%= link_to '(Edit)', member_path(member), 'data-turbolinks': false %></td>
          <td><%= member.email %></td>
          <td><%= member.normalized_phone_number %></td>
          <td><%= member.member_type %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <nav aria-label="Page navigation">
    <ul class="pagination justify-content-center">
      <%= paginate @members %>
    </ul>
  </nav>
</div>

app/views/members/new.html.erb
<div class="container mt-4">
  <%= form_for :member do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.label :member_type %>
      <%= f.select :member_type, options_for_select(["volunteer", "student"]), class: "form-control", required: true %>
    </div>

    <div class="form-group">
      <%= f.submit "Submit", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/members/show.html.erb
<div class="container mt-4">
  <h1>Member Profile</h1>

  <%= form_for @member do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", value: @member.name %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", value: @member.email %>
    </div>

    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, class: "form-control", value: @member.phone_number %>
    </div>

    <div class="form-group">
      <%= f.label :archived %>
      <%= f.check_box :archived, class: "form-control", checked: @member.archived? %>
    </div>

    <div class="form-group">
      <%= f.submit "Save Changes" %>
    </div>
  <% end %>
</div>